# Generated by Django 6.0.7 on 2026-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liverecord',
            name='thoughts',
        ),
        migrations.AddField(
            model_name='liverecord',
            name='emotion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='liverecord',
            name='impression',
            field=models.TextField(blank=True),
        ),
    ]
