# Generated by Django 6.0.7 on 2026-09-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0002_remove_liverecord_thoughts_liverecord_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liverecord',
            name='emotion',
            field=models.CharField(choices=[('最高', '最高'), ('楽しかった', '楽しかった'), ('感動', '感動'), ('普通', '普通'), ('残念', '残念')], max_length=20),
        ),
    ]
