# Generated by Django 6.0.7 on 2026-09-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0003_alter_liverecord_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='record_photos/'),
        ),
    ]
