# Generated by Django 6.0.7 on 2026-09-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0004_alter_recordphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livevenue',
            name='venue_name_kana',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
