# Generated by Django 6.0.7 on 2026-10-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livecalendar', '0005_livevenue_venue_name_kana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='song_order',
        ),
    ]
